working_directory: .cache

run:
  # - data.air_pollution.pdl.cleaned
  # - data.meteo.cleaned
  # - data.spatial.iris
  # - data.bdtopo.cleaned
  # - data.matsim.roads.cleaned
  # - data.matsim.emissions.cleaned
  # - data.receivers.raw
  # - scenario.output
  - scenario.run
  # - scenario.grid
  # - scenario.roads.processed

config:
  processes : 14

  sirane_binary: /home/valoo/Projects/IFSTTAR/_SIRANE/SIRANE-Univ_G.Eiffel/sirane-rev146-Linux-UnivGEiffeil

  regions: []
  departments: [44]

  air_pollution_source: pdl
  air_pollution_year: 2021

  meteo_year: 2021

  bd_topo_zone_file: /home/valoo/Projects/IFSTTAR/_SIRANE/test_rue_ouvertes/ZONE.shp

  receivers_source: matsim
  receivers_file: /home/valoo/Projects/IFSTTAR/_SIRANE/test_rue_ouvertes/RECEIVERS.shp

  matsim_simulation_path: /home/valoo/Projects/IFSTTAR/_SIRANE/matsim_nantes_edgt_1p/nantes_commune/simulation_output
  matsim_detailed_link_path: /home/valoo/Projects/IFSTTAR/_SIRANE/matsim_nantes_edgt_1p/nantes_detailed_network.csv

  output_path: /home/valoo/Projects/IFSTTAR/_SIRANE/sirane_nantes_2021
