working_directory: .cache

run:
  # - data.air_pollution.pdl.cleaned
  # - data.meteo.cleaned
  # - data.spatial.iris
  # - data.bdtopo.cleaned
  # - data.matsim.roads.cleaned
  # - data.matsim.emissions.cleaned
  # - data.receivers.raw
  # - scenario.output
  # - scenario.run
  # - scenario.grid
  # - scenario.roads.processed
  - urban.process.run

config:
  processes : 14

  pollutants: ["PM10"]

  sirane_binary: D:/SYMEXPO/sirane/SIRANE-Univ_G.Eiffel/sirane-rev146-Win64-UnivGEiffeil.exe
  urban_binary: D:/SYMEXPO/sirane/URBAN/URBAN.exe

  regions: []
  departments: [44]

  air_pollution_source: pdl
  air_pollution_year: 2021

  meteo_year: 2021

  zone_file: D:/SYMEXPO/sirane/test_rue_ouvertes/ZONE.shp
  
  receivers_source: matsim
  receivers_file: D:/SYMEXPO/sirane/test_rue_ouvertes/RECEIVERS.shp

  matsim_simulation_path: D:/SYMEXPO/matsim-nantes/edgt_1p/nantes_commune/simulation_output
  matsim_detailed_link_path: D:/SYMEXPO/matsim-nantes/edgt_1p/nantes_detailed_network.csv

  output_path: D:/SYMEXPO/sirane/scenarios/nantes_2021
